### ISSUE TITLE
Game Over Menu Widget

### ISSUE THREAD

**Issue by toemily** [woodRock/front-of-house-frenzy#96]
## Goal
Create a Game Over widget. This widget is presented when the player losses a level.

## Task list: 
- [x] Game Over widget 
- [x] Widget Navigation
- [x] Widget Animations

## Completion criteria: 
There is a game over widget. With aninmations and navigation to restart a a level and quit to main menu,

**Comment by woodRock** [comment]
We have implemented a basic gameover menu widget. The functionality and animations were tested by adding a key to display this menu.

**Comment by woodRock** [comment]
The speed of the animations was too slow. We have added a variable that is visible in the details window. This adjusts the animation speeds for each of the hover animations.
